name: Run Prophet AI Prediction Pipeline

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  run-prophet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Execute Prediction Script
        env:
          FIREBASE_SERVICE_ACCOUNT: 	3MvKBHBy6ReIvsIpWUvxZ4YuIKW4QBiLlpazEqY7
          TDX_CLIENT_ID: st490011-9dff7012-84f0-40fa
          TDX_CLIENT_SECRET: 2df3f2f1-7eae-4d85-8746-9f14b8d2ea30
          CWA_API_KEY: CWA-9C6F2669-C7C4-463B-9118-0D814480EDE0
        run: |
          python 腳本/predict.py
